# Generated by Django 4.1.4 on 2023-01-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
