# Generated by Django 4.1.4 on 2023-01-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_book_genre_remove_book_year_author_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
