# Generated by Django 4.1.4 on 2023-01-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_student_grade_alter_author_alive_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='senior',
        ),
    ]
